CREATE DATABASE HOTEL
USE HOTEL

CREATE TABLE ROOMTYPES(
ID INT PRIMARY KEY IDENTITY,
ROOMTYPE NVARCHAR(255)
)

CREATE TABLE ROOMS(
ID INT PRIMARY KEY IDENTITY,
RoomNumber INT UNIQUE,
ROOMTYPEID INT REFERENCES ROOMTYPES(ID)
)
CREATE TABLE CUSTOMERS(
ID INT PRIMARY KEY IDENTITY,
FULLNAME NVARCHAR(255),
PHONENUMBER NVARCHAR(255)
)
CREATE TABLE RESERVATIONS(
ID INT PRIMARY KEY IDENTITY,
CustomersID INT REFERENCES CUSTOMERS(ID),
ROOMİD INT REFERENCES ROOMS(ID)
)
CREATE TABLE PAYMENTS(
ID INT PRIMARY KEY IDENTITY,
CustomersID INT REFERENCES CUSTOMERS(ID),
)
CREATE TABLE SPENDINGS(
ID INT PRIMARY KEY IDENTITY,
CustomersID INT REFERENCES CUSTOMERS(ID)
)

INSERT INTO ROOMTYPES
VALUES('KING'),
('COOL'),
('STANDART')
INSERT INTO ROOMS
VALUES(232,001),
(222,002),
(212,003)
INSERT INTO CUSTOMERS
VALUES('Mehemmed Ceferzade',+994502100110),
('ELI VELIYEV',+994502124422),
('Emil Hacizade',+944502112111)
INSERT INTO RESERVATIONS
VALUES(0001,01),
(0002,02),
(0003,03)
INSERT INTO PAYMENTS
VALUES(0001),
(0002),
(0003)
INSERT INTO SPENDINGS
VALUES(0001),
(0002),
(0003)

CREATE VIEW CUSTOMERVIEW AS
SELECT * FROM CUSTOMERS


CREATE PROCUDURE  HOTELPRO @ROOMTYPESID INT
AS
SELECT ROOMTYPE FROM ROOMTYPES WHERE @ROOMTYPESID = ROOMTYPES.ID

EXEC HOTELPRO 01


CREATE FUNCTION SHOWNUMBER(@CUSTOMERID INT)
RETURNS NVARCHAR
BEGIN
	 DECLARE @NUM NVARCHAR(50)
	 SELECT @NUM=PHONENUMBER FROM CUSTOMERS WHERE CUSTOMERS.ID=@CUSTOMERID
	 RETURN @NUM
END

SELECT dbo.SHOWNUMBER(0002) 

INSERT INTO CUSTOMERS
VALUES('CEFERLI CEFER',0509990099)
CREATE TRIGGER SHOWINFO
ON CUSTOMERS
AFTER INSERT
AS
BEGIN 
	SELECT * FROM CUSTOMERS
	END







DROP TABLE ROOMTYPES
DROP TABLE ROOMS 
DROP TABLE RESERVATIONS
DROP TABLE CUSTOMERS
DROP TABLE PAYMENTS
DROP TABLE SPENDINGS
